README.md, src/aggregationinfo.cpp
Using Ubuntu 16.04, I encountered an error while building the library:
`Makefile:127: recipe for target 'all' failed`
The fix is to remove 'const' from line 289 in  src/aggregationinfo.cpp:
`std::set<const BLSPublicKey> pubKeysDedup;`
In addition, I added 'mkdir build' to README.md to complete the build instructions.
=> Pull request to fix 'Makefile:127: recipe for target 'all' failed'

contrib/relic/src/pp/relic_pp_map.c
Description from commit:
```
When these are called with thousands of pairings, dynamic allocation on
the stack results in stack overflows, leading to crashes.
Better to use heap allocation here.
```
If this is merged into this repo, I'll also create a PR into the relic project.
=> Use malloc instead of dynamic allocation on-stack in pairing functions

contrib/relic/src/epx/relic_ep2_util.c, python-bindings/pythonbindings.cpp, python-bindings/test.py, src/aggregationinfo.cpp, src/bls.cpp, src/bls.hpp, src/blsprivatekey.cpp, src/blsprivatekey.hpp, src/blspublickey.cpp, src/blspublickey.hpp, src/blssignature.cpp, src/blssignature.hpp, src/blsutil.hpp, src/chaincode.cpp, src/chaincode.hpp, src/extendedprivatekey.cpp, src/extendedprivatekey.hpp, src/extendedpublickey.cpp, src/extendedpublickey.hpp, src/test.cpp
operator< was the only reason why BLSSignature and BLSPublicKey had too keep internal serialized data up-to-data. This required calling of CompressPoint even if the data was never actually needed.
This PR is a set of refactorings which in the end remove the need for operator< and then finally removes the operator and the data field. 
It also includes a few other refactorings to reduce the amount of copying and serialization needed when sorting public keys and signatures. There is also a fix for a memory leak included.
I also removed the stl-like api (begin/end/size) as the classes were probably never intended to be used in a stl-compatible manner (and thus should not imply compatibility if there is none really). I had to change the python tests for this, but could not test these changes …
=> Avoid pre-compressing points and remove the need for operator<

CMakeLists.txt
This might result in code not running on other CPUs than the host CPU.
Also fails to cross-compile for ARM.
Benchmarks don't show any measurable performance loss.
=> Don't use -march=native and -mtune=native when compiling

contrib/relic/src/ep/relic_ep_map.c, contrib/relic/src/ep/relic_ep_pck.c, contrib/relic/src/epx/relic_ep2_map.c, contrib/relic/src/epx/relic_ep2_pck.c, contrib/relic/src/fp/relic_fp_inv.c
These are mostly compilation errors and a few fixes for memory leaks.
I encountered these while trying to build and test the library with ALLOC=DYNAMIC. This PR only fixes the issues which I found in the relic source. There are much more issues with the BLS library, but I'm not going to create a PR for those...these required much more changes. And instead of fixing the issues on that level, I'd suggest to implement small C++ wrappers around relic::bn_t, relic::ep_t and relic::ep2_t which do the appropriate relic::xxx_new/relic::xxx_free calls in constructors/destructors. This way you'd catch all possible memory leaks and clean up the code as well.
I decided to create this PR so that whenever you decide to backport the `ep_map` related changes to upstream, these changes are included.
And …
=> Fix multiple errors in Chia related changes to relic if ALLOC!=AUTO

python-bindings/pythonbindings.cpp, src/aggregationinfo.cpp, src/aggregationinfo.hpp, src/bls.cpp, src/bls.hpp, src/chaincode.hpp, src/extendedprivatekey.cpp, src/extendedprivatekey.hpp, src/extendedpublickey.cpp, src/extendedpublickey.hpp, src/privatekey.cpp, src/privatekey.hpp, src/publickey.cpp, src/publickey.hpp, src/signature.cpp, src/signature.hpp, src/test-utils.hpp, src/test.cpp, src/util.hpp
Don't use namespaces libsodium or relic for C types/functions.
Don't wrap C header files inside those namespaces to avoid possible future issues
=> Remove use/wrapping of C includes with libsodium and relic namespace

src/bls.cpp, src/bls.hpp, src/util.hpp
This is useful when the surrounding application already has a framework for secure allocation (e.g. Bitcoin/Dash LockedPool).
=> Allow setting secure allocator from outside

python-bindings/pythonbindings.cpp
Conversion like "std::string(b)" result in a temporary r value with a
short/undefined lifetime. Accessing data of it via pointers into internal
data gives undefined behavior.
The fix is to use a temporary variable which has a well defined lifetime.
The issue that is fixed here is that even when "from_xxx" methods were
called with the same data, the resulting keys were different each time.
I assume this was not noticed before as it only appear to happen with
some compiler versions.
=> Fix invalid access to data in rvalues when converting py::bytes

SPEC.md
Hi! I am making my own implementation of this and just noticed that the current (previous to this PR) value that's showing here for signature aggregation is actually the `sig2` value from the test vectors. The aggregated sig value that should be looks more like `0x0a638..bc658` (this is in the Python code and matches my own implementation).
I have some other small adjustments to make but plan to save those for later all at once, but this one I felt was important to be changed sooner rather than later because as-is it will confuse anyone trying to implement the spec. There may be other adjustments that need to be made as well, I've only gotten to this first test as far as signature aggregation goes. Thanks!
=> Use correct aggSig value for test vector

.gitignore, contrib/relic/cmake/eb.cmake, contrib/relic/cmake/fb.cmake, contrib/relic/include/relic_conf.h.in
This prevents pip from choking on the build output like so:
```
$ pip3 install --user blspy==0.1.5
Collecting blspy==0.1.5
Using cached https://files.pythonhosted.org/packages/1d/29/3bb073a1d4571989e6a88703cb7f28d39f73bf097d4402c3859edb9868cf/blspy-0.1.5.tar.gz
Building wheels for collected packages: blspy
Running setup.py bdist_wheel for blspy ... error
Failed building wheel for blspy
Running setup.py clean for blspy
Failed to build blspy
Installing collected packages: blspy
Running setup.py install for blspy ... error
Exception:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pip/compat/__init__.py", line 73, in console_to_str
return s.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 25: invalid continuation byte …
```
=> Convert relic stuff to UTF-8

.gitignore, js-bindings/CMakeLists.txt, js-bindings/README.md, js-bindings/blsjs.d.ts, js-bindings/package-lock.json, js-bindings/package.json, js-bindings/tests/AggregationInfo.spec.js, js-bindings/tests/ChainCode.spec.js, js-bindings/tests/ExtendedPrivateKey.spec.js, js-bindings/tests/ExtendedPublicKey.spec.js, js-bindings/tests/PrivateKey.spec.js, js-bindings/tests/PublicKey.spec.js, js-bindings/tests/Signature.spec.js, js-bindings/tests/Threshold.spec.js, js-bindings/tests/typings.spec.ts, js_build.sh
Commit messages should explain what happened on each step, but here is a gist:
* Wasm is a separate file now and is not bundled inside of JavaScript
* WebAssembly instantiation is now asynchronous and works in modern browsers (see #76)
* Above causes major API change
* Compilation was tweaked to produce smaller output
* JS build script was tweaked to work on any machine with Emscripten installed regardless of specific location
* Minor tweaks to package.json and version bump
Fixes #76
=> Wasm port improvements

README.md, python-bindings/README.md, python-bindings/test.py, setup.py, src/signature.cpp
Deserializing a PrependSignature as a Signature should throw an error.
=> Add extra check for signature deserialization

js-bindings/README.md
The links are currently leading to "page not found" (404).
=> Fix relative links in README of js-bindings

.github/workflows/build.yml, pyproject.toml, windows-build.sh
Github actions to build, test, and upload mac and linux wheels.
Windows compiles, tests, but does not pytest or build wheels.
=> Build wheels on mac & linux, clean compile windows

.github/workflows/build.yml
This builds binary wheels for macos and linux for both python 3.7 and 3.8.
=> Build python 3.8 binary wheels

contrib/relic/include/relic_alloc.h
Tested on FreeBSD amd64 11.3 and 12.1.
=> Include stdlib.h instead of alloca.h on FreeBSD

src/CMakeLists.txt
Fixed for broken relic?
Looks like something bad happened here
https://github.com/relic-toolkit/relic/commit/bb41dc8871244c9abd23268ca065d459a68b79eb
=> regress relic

src/schemes.cpp, src/schemes.hpp
At the moment public key aggregation is only possible through the "+" operator override. This is extremely slow for large quantities of public keys.
This pull requests adds a dedicated aggregation function for public keys.
The speedup factor running a smaller benchmark already resulted in around 25x
---- Old------
PopScheme verification
Total: 500 runs in 74 ms
Avg: 0.148 ms
---- New------
PopScheme verification
Total: 500 runs in 3 ms
Avg: 0.006 ms
=> Add fast pub aggregation

src/privatekey.cpp, src/privatekey.hpp
add assignment operators to properly copy value (instead of pointer) or move (instead of copying pointer, resulting in double-free)
=> fix resource management in PrivateKey class

.github/workflows/build-aarch64.yml, .github/workflows/build.yml, CMakeLists.txt, README.md, python-bindings/pythonbindings.cpp, src/CMakeLists.txt
- Now, if libsodium is found the build process will default to dynamically linking libsodium. This should ease cross platform building.
- If $CIBUILDWHEEL is set in the environment, libsodium will be statically linked. That is the default when building binary wheels on ci.
- Moved valgrind to test the statically linked libsodium version of bls-library.
- "By hand" (using strings) validated the published wheels for all four targets are getting statically linked from cibuildwheel.
- Have relic upstream a fix to FreeBSD and OpenBSD
-Correct "DSEED" typo - though note that "SEED" defaults to the correct random device so there should be no historical issue.
=> Default to dynamically linking libsodium, static link on wheels

src/elements.cpp, src/elements.hpp, src/privatekey.cpp, src/schemes.cpp
=> src: Avoid using `g1_t` and `g2_t` pointer if not required

python-bindings/pythonbindings.cpp, src/elements.cpp, src/hdkeys.hpp, src/privatekey.cpp, src/schemes.cpp, src/test.cpp, src/util.hpp
=> src|python: Force explicit construction of class `Bytes`

.gitmodules
This is just confusing because its the `Chia-Network` fork and its not really related to the relic version that cmake pulls.
=> git|contrib: Drop relic submodule

src/test-bench.cpp
This is meant to cover the validation of keys that have to happen in practice, in addition to validating the signature. The validation happens in `FromBytes()`.
=> benchmark G1 and G2 subgroup validation

src/test-bench.cpp, src/test-utils.hpp
I don't think there's a good reason to use `double` to count iterations. It's inherently an integer.
=> use int instead of double for counting test iterations

.github/workflows/relic-nightly.yml, src/CMakeLists.txt, src/test.cpp
It seems it used to be `master`.
`relic_test.h` now defines a macro called `TEST_CASE` which conflicts with catch's macro with the same name. It doesn't seem like we need anything out of that header though.
=> relic's main branch is "main"

src/bls.cpp, src/test.cpp
`core_set_thread_initializer` is only defined if macro `MULTI != RELIC_NONE` evaluates true but `bls.cpp` takes the presence of `core_set_thread_initializer` for granted. This resolves that issue.
Tested on `Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64`
* https://github.com/dashpay/bls-signatures/pull/13 ("Don't call core_set_thread_initializer if not defined" by kittywhiskers)
* https://github.com/dashpay/bls-signatures/commit/f208c6764a89959890f3f7970812eb27cd6bba00 ("src|test: Fix multithreading availability checks" by @xdustinface)
=> Ensure relic_core_initializer call is thread-aware

src/elements.cpp, src/elements.hpp
`ep_map_dst()` and `ep2_map_dst()` ought to return valid points, the validation of their output is redundant (and expensive).
These are my timings before and after this change:
```
Batch verification
Total: 100000 runs in 133637 ms
Avg: 1.33637 ms
```
```
Batch verification
Total: 100000 runs in 73739 ms
Avg: 0.73739 ms
```
=> remove redundant validation checks

src/CMakeLists.txt, src/elements.cpp
New versions of relic includes an optimized subgroup check for G1 and G2. Not only do we not need to do our own subgroup check, but we also get a good speedup by just upgrading relic.
In `main` right now, our `IsValid()` call is dominated by the cost to `g1_is_valid()` and `g2_is_valid()` calls (>90% of the time is spent in those calls).
Here's a comparison between just the current version of relic vs. head of `main` (both with this patch to `IsValid()`):
```
Public key validation
Total: 100000 runs in 33414 ms
Avg: 0.33414 ms
Signature validation
Total: 100000 runs in 68799 ms
Avg: 0.68799 ms
```
```
Public key validation
Total: 100000 runs in 14181 ms
Avg: 0.14181 ms
Signature validation
Total: 100000 runs in 18321 ms
Avg: 0.18321 ms
```
=> Simplify IsValid()

CMakeLists.txt
Quick update to reflect that RELIC changed naming of a variable to be closer to CMake conventions.
=> Update to RELIC's change from COMP to CFLAGS.

CMakeLists.txt, README.md, src/CMakeLists.txt, src/privatekey.cpp, src/test.cpp
Minor fixes to take into account recent changes in RELIC:
* Rename `master` branch to `main`
* Remove unnecessary include of `relic_test.h`
* Replaced recently renamed `bn_init` with something simpler (assuming that `ALLOC == AUTO` remains in place)
=> Fix support to latest version of RELIC

.gitignore, js-bindings/README.md, js-bindings/blsjs.d.ts, js-bindings/jsbindings.cpp, js-bindings/package.json, js-bindings/wrappers/G1ElementWrapper.cpp, js-bindings/wrappers/G1ElementWrapper.h, js-bindings/wrappers/G2ElementWrapper.cpp, js-bindings/wrappers/G2ElementWrapper.h, js-bindings/wrappers/PrivateKeyWrapper.cpp, js-bindings/wrappers/PrivateKeyWrapper.h, js-bindings/wrappers/UtilWrapper.cpp, js-bindings/wrappers/UtilWrapper.h
Related to #220 
Typings for js-binding is broken and too old.
I've updated type declarations and added some methods which should be exposed.
See diffs in this PR.
This PR does not include test specs corresponding to the updates.  
So merging this PR doesn't mean it's OK to publish to npm. Just a beta version at the best.
I decided to leave test specs untouched because I think my updates need to be cross checked by creating new test specs by someone else.
So please add test specs after this PR is merged to main branch.
```javascript
// bls-signatures/js-bindings/package.json
{
"name": "bls-signatures",
"version": "0.2.1-beta.0", // <- Set to 0.2.1-beta.0 from 0.2.0.
...
}
```
~~More specifically, I changed method name `fromBytes` to `from_bytes`. (python bindings is using name …
=> Fix js typings

js_build.sh
Failed to build js-bindings via `js_build.sh`
```shell
$ git clone https://github.com/Chia-Network/bls-signatures
$ cd bls-signatures
$ ./js_build.sh
CMake Error at /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:99 (message):
Could not find toolchain file:
/PATH_TO_EMSDK/emsdk/upstream/emscripten/emcc/cmake/Modules/Platform/Emscripten.cmake
Call Stack (most recent call first):
CMakeLists.txt:12 (project)
```
```shell
cmake ../ -DCMAKE_TOOLCHAIN_FILE=$(realpath $(which emcc))/cmake/Modules/Platform/Emscripten.cmake
```
The Emscripten root specified in `CMAKE_TOOLCHAIN_FILE` is wrong.
`$(realpath $(which emcc))` should be `$(dirname $(realpath $(which emcc)))`
https://youtu.be/rQlBDzBLP-4
=> Fixed wrong toolchain file path in js_build.sh

.github/workflows/relic-nightly.yml, js-bindings/wrappers/BignumWrapper.cpp, src/CMakeLists.txt
This will now test MacOS, Python, Javascript in addition to the C++ on Ubuntu against Relic/main every night.
It moves the regular Relic build has to the same one proposed in PR #244
=> Add MacOS, Python, Javascript tests to Relic Nightly

js-bindings/wrappers/BignumWrapper.cpp, src/CMakeLists.txt
We tested and fixed for #194 but we forgot to pull relic forward in 1.0.3. This moves Relic to https://github.com/relic-toolkit/relic/commit/e6209fd80e07203b865983faee635fa1f85d6c9f which passes the nightly build - https://github.com/Chia-Network/bls-signatures/actions/runs/1017828297 .
=> Bring Relic to e6209f

src/elements.cpp
This patch handles RELIC errors when invalid inputs are provided.
=> Add fix for RELIC parsing invalid inputs.

src/CMakeLists.txt, src/elements.cpp
Recent changes to Relic caused an issue that @guidovranken flagged and @dfaranha fixed - #247 
This PR moves the targetted/pinned version of Relic to the fixed Relic commit - https://github.com/relic-toolkit/relic/commit/7ed8e702db74d5d5a83b0bfaf9ee8e33a70e36ed as requested by @dfaranha
=> Update Relic for G1 fix

src/CMakeLists.txt
It also gracefully handles the case when a directory already exists.
=> Use CMake's builtin create directory function

python-bindings/pythonbindings.cpp, python-bindings/test.py
This is needed for plots caching in `chia-blockchain`.
=> python-bindings: Add `pickle` support for `G1Element`

python-bindings/pythonbindings.cpp, python-bindings/test.py
This reverts commit 616230cefa8135e72607d196e749c6ffb517bd4c which is not longer needed because plot data caching (https://github.com/Chia-Network/chia-blockchain/pull/8009) is now done without `pickle`.
=> Revert "python-bindings: Add `pickle` support for `G1Element` (#265)"

src/util.hpp
util.hpp: In static member function ‘static std::string bls::Util::HexStr(const uint8_t*, size_t)’:
util.hpp:62:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
62 |         for (int i=0; i < len; ++i)
=> fix some gcc compiler warnings when using -Wsign-compare

src/privatekey.cpp, src/test.cpp
Introduced in #168.
The copy assignment operator does not invalidate the caches.
This could dangerously lead to situations where a `PrivateKey` returns wrong G1/G2 elements (if they were cached before the copy).
=> Bug: invalid G1 and G2 cached in PrivateKey

python-impl/ec.py, python-impl/pairing.py
* Removing an outdated comment standing in conflict with the code. 
* Taking the chance of completing some sentences in the other docs there as well.
The doc suggests the standard secp256k1 is being used as default, but actually more recent curve parameters are used in the line below. 
There's actually two identical such docs being removed, one in the `ec` file and one in the `pairing` file. As far as I can see, nothing should stand in the way or importing one of them in the other (e.g. removing the one in the `pairing` file and there importing it from `ec`). 
(The module level [constants should](https://www.python.org/dev/peps/pep-0008/#constants) also be all caps, as in `DEFAULT_EC`. At least I think it's a constant.)
----
Some notes for those files unrelated to the docs. 
* I wonder if …
=> Remove outdated ECC docs line

python-impl/private_key.py
This is a minor change. When converted to hex for display purposes - the python hex() call will remove leading zeros. This can lead to some minor inconsistency between the display of the PrivateKey and the display of the bytes. For example:
`print(f"{key}")` would display `PrivateKey(0xba5a1381d6718d15b6e3122344c3f71ab3f6f7d12dfc7b8a6856b9404007a04)`
`print(f"{bytes(key).hex()}")` would display `0x0ba5a1381d6718d15b6e3122344c3f71ab3f6f7d12dfc7b8a6856b9404007a04`
This PR resolves this by making sure the string representation will match the bytes representation
=> Make string output of the pk consistent wrt leading 0

python-impl/ec.py
In the pure-Python implementation, adding points which lead to the infinity triggers an exception:
Traceback (most recent call last):
File "bls-signatures/python-impl/ec.py", line 55, in __add__
return add_points(self, other, self.ec, self.FE)
File "bls-signatures/python-impl/ec.py", line 350, in add_points
return AffinePoint(FE.zero(), FE.zero(), True, ec)
TypeError: zero() missing 1 required positional argument: 'Q'
This is because `FE.zero` needs to be called with `ec.q`.
Add the missing parameter to the call.
=> Provide parameter to FE.zero

.github/workflows/build-aarch64.yml, .github/workflows/build-test.yaml, .github/workflows/build-wheels.yml
* Update cibuildwheel to v2.2.2
* Build wheels for 3.10 (except M1)
Draft for:
- It isn't apparent that pybind11 supports the stable ABIs.
=> Also build Python 3.10 wheels

.github/workflows/build-aarch64.yml, .github/workflows/build-m1-wheel.yml, .github/workflows/build-test.yaml, .github/workflows/build-wheels.yml
As is this builds on any push and also any PR.  This results in double workflows on PRs.
=> Build on main, tags, and PRs

python-impl/README.md
Updated the URL to [Pairings for Beginners](https://static1.squarespace.com/static/5fdbb09f31d71c1227082339/t/5ff394720493bd28278889c6/1609798774687/PairingsForBeginners.pdf) in the README. Fixes #308.
=> Updated the pairings tutorial URL

python-bindings/pythonbindings.cpp, python-bindings/test.py, src/elements.cpp, src/elements.hpp, src/schemes.cpp, src/test.cpp
The validity check is now performed at signature validation time instead of element creation time. The from_bytes methods are still there, but they are no longer needed, due to the more efficient from_bytes_unchecked methods.
2000 pks parse time:
before: 0.5s
after: 0.09s
=> Ms.from bytes unchecked

python-bindings/pythonbindings.cpp, src/elements.cpp, src/elements.hpp, src/util.hpp
make our span-like type (`Buffer`) more span-like and when we need to make copies of (fixed size, small) buffers, make them on the stack rather than in fresh heap allocations.
=> lighter-weight buffer handling

python-impl/ec.py
If not fixed it may cause some issues, e.g. C_bit will be =128 instead of =1 or S_bit =32 instead of =1.
The shift removes the trailing zeros in order to get just a single bit.
=> Fix bit in point deserialization (pure Python)

python-bindings/pythonbindings.cpp, src/elements.cpp, src/elements.hpp
We sometimes serialize and deserialize `GTElements` to pass them across process boundaries. Specifically, when the mempool validates a transaction, it does so in a separate process and receives the new BLS cache entries back from that process (in serialized form). Since we trust the other process (it's also part of the full node), we don't have to validate the `GTElement` when inserting it into the main BLS cache.
This overload adds symmetry with `G1Element.from_bytes_unchecked()` and `G2Element.from_bytes_unchecked()`
=> Gt element unchecked

python-impl/ec.py
Yesterday I was messing around with bls-signatures python impl and bindings and noticed that in the python impl when a AffinePoint is turned into bytes it doesn't handle it like it handles a JacobianPoint turned into bytes. Even though the process is exactly the same as the first thing that is done to the Jacobian is it is turned into Affine.
=> Allow AffinePoint to be correctly turned into bytes

.github/workflows/build-test.yaml, .github/workflows/js-bindings.yml, .github/workflows/relic-nightly.yml
Update deprecated github actions to versions that support Node 16
=> Node v16 updates

src/test.cpp
Thanks to @knst for bringing attention to it in #358
=> Fix a typo in class PrivateKey testcase

python-bindings/pythonbindings.cpp, python-bindings/test.py
the python binding for `G1Element.from_message()` and `G2Element.from_message()` don't work currently, and there's no test coverage for them.
This patch fixes them and adds test coverage.
=> fix python binding for from_message() on G1Element and G2Element

src/schemes.hpp
Signing commit from @knst from https://github.com/Chia-Network/bls-signatures/pull/359
=> fix: add missing destructor for CoreMPL and final for nested classes

python-bindings/test.py, src/elements.cpp, src/elements.hpp
Fix up GTElement operator& pairing mode.
All python tests now pass
=> Fix pairing with operator&

CMakeLists.txt, src/elements.cpp, src/test.cpp
Make sure to use`_add_or_double` rather than just `_add`. This properly supports creating an aggregated signature with the same sig.
Added test case that tests this functionality
Also, pin BLST to revision `a8cd361c9f671577aeab3f074098443af92a53fc` as very recent changes in `origin/master` cause some compilation issues.
=> Use _add_or_double instead of just _add and pin BLST to specific revision

src/test.cpp
Add in some test cases to exercise some parts of the C++ code that are currently not covered.
=> Add in some small test cases

emsdk_build.sh, js_build.sh
Example `Build JS`:
* Before: ~4m 35s
* After: ~1m 38s
Example `Build and Test on ubuntu-latest CPython 3.11`:
* Before: ~4m 52s
* After: ~1m 57s
=> Significantly speedup javascript bindings tasks by skipping libbls tests and benchmarks

.github/workflows/build-wheels.yml, CMakeLists.txt, python-bindings/CMakeLists.txt, setup.py, src/CMakeLists.txt
* Speedup the process of creating wheels by skipping the compiling and linking of `libbls`' tests and benchmarks.
* We no longer need Windows-specific `CMake` version checking in `setup.py`.
* We no longer need Windows-specific architecture flag passing in `setup.py`.
* We no longer treat Windows in a special way w.r.t. compiling and linking in `setup.py`.
* We no longer need Windows-specific preparations before starting the process of creating wheels.
* We no longer need Windows-specific repairs after wheels creation.
* We no longer need the `relic_ietf_64` repository and its related tasks.
Dedicated to @wjblanke
=> Streamline the processes of building libbls, testing it, and creating the blspy wheels

.github/workflows/build-wheels.yml
It looks like the windows steps are missing.
=> Update build-wheels.yml to add Windows pre processing back

.github/workflows/build-blst-nightly.yml
This needs #412 which we'll get when it lands on main.
=> Fix the Windows flow and improve the others

.github/workflows/build-blst-nightly.yml, CMakeLists.txt, python-bindings/CMakeLists.txt
Adding back a nightly test of our upstream dependency
=> Add back nightly testing of blst dependency

src/test.cpp
Add test and some comments for AugScheme aggregation
=> Add test for AugScheme aggregation and comment

.github/workflows/build-wheels.yml, pyproject.toml
Puts most `cibuildwheel` configuration into `pyproject.toml` instead of using envvars in the github actions.
The rationale is that this makes it a little bit easier to build the wheel locally for debugging and testing as there is less configuration specific to GH actions
Note some of the envvars refer to GH action matrix items, so those remain in the GH workflow.
=> Use pyproject.toml instead of envvars for cibuildwheel

.github/workflows/build-test.yaml, .github/workflows/build-wheels.yml
Changed MACOSX_DEPLOYMENT_TARGET to macOS 11
Remove python 3.7
=> Update macOS target to macOS 11 and remove python 3.7

.github/workflows/build-wheels.yml
Consolidating wheels to cibuildwheel 2.11.2
This is the last version that uses bash in windows, which is needed for some scripts. The scripts could be edited to work in powershell, but this is left for another day
=> Update to cibuildwheel 2.11.2

CMakeLists.txt
Update to BLST `v0.3.11` release commit.
Several fixes and some possible small speed improvement on ARM Macs compiled in portable mode per https://github.com/supranational/blst/issues/172
=> Update CMakeLists.txt for blst `v0.3.11` release

README.md
Add some data about blst
Clean up which platforms are supported
Switch to Discord
Remove lgtm reference
=> Catch README.md up to current day

.github/workflows/build-test-riscv64.yml
Use the CNI docker image based on Ubuntu for building riscv
=> Use CNI ubuntu riscv docker image

python-bindings/CMakeLists.txt
Cmake is deprecating the way pybind finds the python interpreter. See https://cmake.org/cmake/help/latest/policy/CMP0148.html and https://github.com/pybind/pybind11/pull/4719
=> Update to pybind v2.11.1

python-bindings/pythonbindings.cpp, python-bindings/test.py, setup.py
this addresses a few issues raised by CodeQL
=> various cleanups

.github/workflows/build-wheels.yml
Add python 3.12 to matrix
remove old exclude of python 3.7 on macOS
upgrade cibuildwheel to 2.16.2 (current latest) needed for python 3.12 support
=> Add python 3.12

.github/workflows/build-wheels.yml
The newest pre 3.0 cibuildwheel needs python 3.8 deprecated
=> Update cibuildwheel to final 2.x version
