Chia-Network/bls-signatures

README.md, python/README.md, python/pythonbindings.cpp, src/aggregationinfo.cpp, src/aggregationinfo.hpp, src/bls.cpp, src/bls.hpp, src/blsprivatekey.cpp, src/blspublickey.cpp, src/blspublickey.hpp, src/blssignature.cpp, src/blssignature.hpp, src/extendedprivatekey.cpp, src/extendedpublickey.cpp, src/test-bench.cpp, src/test.cpp
Removes all using statements from source code.
=> Clean up using statements

src/aggregationinfo.cpp
Fixes https://github.com/Chia-Network/bls-signatures/issues/38
=> Only delete tree entries when the tree isn't empty.

contrib/relic/src/ep/relic_ep_util.c, contrib/relic/src/epx/relic_ep2_util.c, src/bls.cpp, src/publickey.cpp, src/signature.cpp, src/test.cpp
See individual commits.
Fixes #40
=> Better error handling for invalid public keys and signatures

src/bls.cpp, src/bls.hpp, src/privatekey.hpp, src/publickey.hpp
This implements primitive support for Diffie-Hellman key exchanges.
=> Implement DHKeyExchange

js-bindings/tests/Threshold.spec.js, python-bindings/README.md, python-bindings/pythonbindings.cpp, python-bindings/test.py, python-impl/README.md, python-impl/keys.py, python-impl/tests.py, python-impl/threshold.py, setup.py, src/test.cpp, src/threshold.cpp, src/threshold.hpp
Adds python bindings for threshold signatures, and InsecureSignature.
=> Threshold python

js-bindings/tests/Threshold.spec.js, js-bindings/wrappers/SignatureWrapper.cpp, js-bindings/wrappers/ThresholdWrapper.cpp
Now all tests of js-bindings are passed.
=> Fix some problems in js-bindings.

CMakeLists.txt, cmake_modules/Findgmp.cmake, cmake_modules/Findsodium.cmake, setup.py
Forces the use of static libraries.
=> Only static dependencies (gmp, libsodium)

.github/workflows/build.yml, python-bindings/pythonbindings.cpp
=> Fix test and macos github actions

.flake8, .github/workflows/build.yml, .gitignore, README.md, mypi.ini, python-impl/signature.py
This removes the errors from lgtm.com around `raise Exception` and adds more source linting.
=> Fix Raise Exceptions - add flake8, mypi

.github/workflows/build-aarch64.yml, .github/workflows/build.yml
=> Move to cibuildwheel 1.6.1

src/CMakeLists.txt
https://github.com/relic-toolkit/relic/issues/163
=> Move to relic/master with their fix

python-bindings/pythonbindings.cpp, setup.py
Correctly quote version define under python 3.9
=> Versioninfowjb

src/bls.cpp, src/bls.hpp, src/elements.cpp
=> src: Throw exceptions instead of std::string, drop some redundant code

.github/workflows/build-aarch64.yml, .github/workflows/build-test.yaml, .github/workflows/build-wheels.yml, python-bindings/CMakeLists.txt
Update to pybind 2.6.2 to avoid a bug in python 3.9.0
=> Use pybind 2.6.2, modernize the CI

README.md, python-bindings/pythonbindings.cpp, src/schemes.cpp, src/schemes.hpp, src/test-bench.cpp, src/test.cpp
Im not yet sure if you use classes this way by intention (if so let me know why, im curious about the reason then) or if this PR is something you want here in the end but while i was reading through all scheme related code i realised there are some ways to refactor the code so that it is (at least in my opinion) easier to read/understand and maintain while it removes quite some duplicated code.
It didn't look like it to me when i read through your style guidelines but feel free to close this if it goes against any of them or so. Doing this still helped me to understand this stuff better which was the initial goal so i won't be too sad 😄
=> refactor: Use class inheritance in scheme.cpp instead of classes with static methods

.github/workflows/build-aarch64.yml, .github/workflows/build-wheels.yml
=> Generate sha256 sums when building wheels

src/schemes.cpp, src/schemes.hpp
Avoid some element creation and copying for no reason, be a bit more descriptive and type correct for some variables, drop some redundant code and simplify + improve readability in some places. Just walk through the commits hierarchically for easier review. Le me know your thoughts or concerns :)
Based on #150.
=> schemes: Some improvements/simplifications

src/privatekey.cpp, src/privatekey.hpp, src/test.cpp
See individual commit messages.
Based on #163 (1254fd6)
=> privatekey|test: Some improvements/fixes in `PrivateKey`

.github/workflows/build-wheels.yml, contrib/catch/catch.hpp
* Also stop attempting to build ARM64 wheels as x86_64 gmp and libsodium won't allow cross compile easily.
* Will build natively on M1 by hand for now
=> Catch catch up for Apple Silicon

src/schemes.cpp
=> schemes: Some improvements and refactoring

src/elements.cpp
=> elements: Some improvements and refactoring

python-bindings/pythonbindings.cpp, python-bindings/test.py, src/elements.cpp, src/elements.hpp, src/schemes.cpp, src/test.cpp
=> src|python: Drop `G1Element::Infinity()` and `G2Element::Infinity()`

src/CMakeLists.txt
03a7c3b7fa43c0da6f3720e341f7d4f6a6d6f21e specifically
=> Update to Relic @ master

.github/workflows/build-aarch64.yml, .github/workflows/build-test.yaml, .github/workflows/build-wheels.yml, .github/workflows/relic-nightly.yml, .gitmodules, README.md, python-bindings/README.md, python-bindings/test.py, python-impl/README.md, python-impl/ec.py, python-impl/fields.py, python-impl/hd_keys.py, python-impl/hkdf.py, python-impl/impl-test.py, python-impl/op_swu_g2.py, python-impl/pairing.py, python-impl/private_key.py, python-impl/schemes.py, setup.py
- Updated and linted all README markdown.
- Switch primary branch to main
- Linted all python
- Removed now vestigial .gitmodules
=> Move to main branch - clean up for 1.0 RC

python-bindings/benchmark.py
example output:
```
Public key validation
Total: 100000 runs in 14212.9 ms
Avg: 0.142129
Signature validation
Total: 100000 runs in 18368.4 ms
Avg: 0.183684
Aggregation
Total: 100000 runs in 196.7 ms
Avg: 0.001967
Batch verification
Total: 100000 runs in 75779.7 ms
Avg: 0.757797
```
=> Python benchmark

js-bindings/package-lock.json, js-bindings/package.json
Updated glob-parent vulnerability as reported by dependabot:
https://github.com/Chia-Network/bls-signatures/security/dependabot/js-bindings/package-lock.json/glob-parent/open
=> update glob-parent version

src/CMakeLists.txt
=> Adapt to the most recent version of emsdk

.gitignore, js-bindings/CMakeLists.txt, src/test.cpp
Scrub a few references to relic
=> Scrub some references to relic

src/hdkeys.hpp, src/test-bench.cpp, src/test.cpp, src/util.hpp
Some minor code cleanup based on CodeQL comments
=> Some CodeQL directed code cleanup

src/elements.cpp, src/schemes.cpp
Some more codeql related cleanup
=> Some more codeql cleanup

src/CMakeLists.txt
=> Add some assembly source files that we'd need for the upcoming nightly build

README.md
Remove LGTM badges and add Coverage and CodeQL badge
=> Remove LGTM badges and add Coverage badge

CMakeLists.txt
Since we now have things building with blst/origin/master, lets pin to current.
=> Update CMakeLists.txt to current blst/master

python-impl/ec.py, python-impl/util.py
Update python code for new flake8 type is checks
=> Update for new flake8 checks

.github/workflows/build-test-riscv64.yml
Build the wheel and upload the artifact if successful
=> Build the wheel and upload the artifact if successful

js-bindings/package-lock.json, js-bindings/package.json
And close out previous snyk PRs
=> Catch up various js dependencies

.github/workflows/build-blst-nightly.yml
https://github.com/Chia-Network/bls-signatures/actions/runs/11468270388
=> install python for blst nightly checks before building instead of after
